package com.november.mcphone.core.script.server;

import com.google.gson.*;
import com.november.mcphone.core.script.net.*;
import com.november.mcphone.core.script.pkg.TrustStore;
import com.november.mcphone.core.script.server.economy.*;
import net.minecraft.server.MinecraftServer;
import net.minecraft.world.level.storage.LevelResource;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.*;

/** 原生管理 RPC。App 能力不能取得管理权；读写都重查在线 OP3 与部署审批 UUID。 */
public final class NativeAdminControls {
    private record Preview(JsonObject operation,String expected,AdminConfiguration.Snapshot before,AdminConfiguration.Snapshot after,List<String> differences,Set<Integer> seen){}
    private final MinecraftServer server;
    private final QuotaControls roles;
    private final AdminConfiguration configs;
    private final AdminConfirmations<Preview> confirmations=new AdminConfirmations<>(System::currentTimeMillis);
    public NativeAdminControls(MinecraftServer server,QuotaControls roles){this.server=server;this.roles=roles;configs=new AdminConfiguration(server.getWorldPath(LevelResource.ROOT),ScriptHost.current().quotas().audit());}
    public void forget(UUID player){confirmations.forget(player);}
    public ScriptRpcResult handle(ScriptRpc rpc,PlayerSnapshot player,JsonObject args)throws IOException {
        if(!roles.allowed(player.uuid()))return ScriptRpcResult.fail(rpc.requestId(),ScriptErrorCode.NOT_AUTHORIZED);
        ScriptHost host=ScriptHost.current();JsonObject out=new JsonObject();
        switch(rpc.actionId()){
            case "admin.list"->{AdminConfiguration.exact(args,"kind","offset","app");List<JsonObject> all=rows(args.get("kind").getAsString(),args.get("app").getAsString());int offset=args.get("offset").getAsBigDecimal().intValueExact();if(offset<0||offset>all.size())throw new IllegalArgumentException("管理分页无效");JsonArray items=new JsonArray();out.add("items",items);out.addProperty("total",all.size());for(int i=offset;i<Math.min(all.size(),offset+8);i++){items.add(all.get(i));if(size(out)>3800){items.remove(items.size()-1);break;}}out.addProperty("next",offset+items.size());}
            case "admin.preview"->{AdminConfiguration.exact(args,"operation");JsonObject operation=args.getAsJsonObject("operation").deepCopy();String kind=operation.get("kind").getAsString();Preview preview;
                if(Set.of("preset","capability","boundary","scripting","network","author","appPolicy","authorUpdates").contains(kind)){var before=configs.read();var after=AdminConfiguration.change(before,operation);preview=new Preview(operation,before.revision(),before,after,AdminConfiguration.differences(before,after),new HashSet<>());}
                else {JsonObject before=mutationState(operation);List<String> lines=new ArrayList<>();AdminConfiguration.addLines(lines,"将修改："+subject(operation));AdminConfiguration.addLines(lines,"现有记录："+before);AdminConfiguration.addLines(lines,"更改内容："+operation);preview=new Preview(operation,hash(before),null,null,List.copyOf(lines),new HashSet<>());}
                String token=confirmations.issue(player.uuid(),rpc.connectionEpoch(),preview);out.addProperty("token",token);page(out,preview,0);
            }
            case "admin.previewPage"->{AdminConfiguration.exact(args,"token","offset");page(out,confirmations.get(player.uuid(),rpc.connectionEpoch(),args.get("token").getAsString()),args.get("offset").getAsBigDecimal().intValueExact());}
            case "admin.commit"->{AdminConfiguration.exact(args,"token");Preview preview=confirmations.get(player.uuid(),rpc.connectionEpoch(),args.get("token").getAsString());for(int i=0;i<preview.differences().size();i+=4)if(!preview.seen().contains(i))throw new IllegalArgumentException("请先查看全部差异");confirmations.consume(player.uuid(),rpc.connectionEpoch(),args.get("token").getAsString());
                if(preview.after()!=null){if(preview.operation().has("app"))auditMutation(player.uuid(),preview.before().file(ScriptRuntimeConfig.FILE),preview.operation());configs.commit(player.uuid(),preview.before(),preview.after());host.publishAdminConfiguration(preview.after());}
                else {JsonObject before=mutationState(preview.operation());if(!hash(before).equals(preview.expected()))throw new IllegalArgumentException("记录已改变，请重新预览");auditMutation(player.uuid(),before,preview.operation());mutate(player.uuid(),preview.operation());}out.addProperty("saved",true);
            }
            default->throw new IllegalArgumentException("管理操作无效");
        }
        if(size(out)>ScriptProtocol.DATA_MAX)throw new IOException("管理响应超额");return ScriptRpcResult.ok(rpc.requestId(),out.toString().getBytes(StandardCharsets.UTF_8),0);
    }
    private static int size(JsonObject value){return value.toString().getBytes(StandardCharsets.UTF_8).length;}
    private static String subject(JsonObject operation){return operation.has("app")?operation.get("app").getAsString():operation.has("id")?operation.get("id").getAsString():"mcphone:configuration";}
    private static void page(JsonObject out,Preview preview,int offset){if(offset<0||offset>preview.differences().size()||offset%4!=0)throw new IllegalArgumentException("差异分页无效");JsonArray rows=new JsonArray();for(int i=offset;i<Math.min(preview.differences().size(),offset+4);i++)rows.add(preview.differences().get(i));preview.seen().add(offset);out.add("differences",rows);out.addProperty("total",preview.differences().size());out.addProperty("next",Math.min(preview.differences().size(),offset+4));}
    private List<JsonObject> rows(String kind,String app)throws IOException {
        ScriptHost h=ScriptHost.current();List<JsonObject> rows=new ArrayList<>();
        switch(kind){
            case "settings"->{var cfg=h.runtime();rows.add(row("server_scripts","服务端脚本",cfg.serverScripts()));rows.add(row("server_fetch","服务器外网",cfg.net().enabled()));rows.add(row("client_fetch","允许客户端外网",cfg.net().clientAllowed()));rows.add(row("cross_server_trust","跨服信任（首版不提供）",false));rows.add(row("preset","预设："+h.capabilities().preset().name().toLowerCase(Locale.ROOT),false));}
            case "permissions"->{var cfg=h.runtime();for(String role:List.of("deployment_approvers","store_reviewers","gift_editors")){Set<UUID> members=switch(role){case "deployment_approvers"->cfg.deploymentApprovers();case "store_reviewers"->cfg.storeReviewers();default->cfg.giftEditors();};for(UUID uuid:new TreeSet<>(members)){JsonObject r=row(uuid.toString(),role+" · "+uuid,true);r.addProperty("note","名单只能编辑服务器文件，再由管理员重载");rows.add(r);}}}
            case "published"->{if(h.store()!=null)for(JsonObject info:h.store().publishedSummaries()){JsonObject r=row(info.get("id").getAsString(),info.get("name").getAsString(),true);r.add("followUpdates",info.get("followUpdates"));r.add("version",info.get("versionCode"));rows.add(r);}}
            case "commands"->{JsonObject cfg=h.commands().snapshot();JsonObject all=row("switches","命令模板总开关",cfg.get("enabled").getAsBoolean());all.addProperty("others",cfg.get("allow_affect_others").getAsBoolean());rows.add(all);for(JsonElement value:cfg.getAsJsonArray("templates")){JsonObject t=value.getAsJsonObject(),r=row(t.get("id").getAsString(),t.get("id").getAsString(),t.has("reviewed")&&t.get("reviewed").getAsBoolean());r.addProperty("note","完整定义请编辑 "+CommandRunner.FILE+" 后重载；参数与节点路径按同一验证器检查");rows.add(r);}}
            case "capabilities"->{for(var e:CapabilityCatalog.all()){JsonObject r=row(e.id(),e.id(),!h.capabilities().isDisabled(e.id()));r.addProperty("available",e.open());r.addProperty("tier",e.tier().name());r.addProperty("note",e.note());rows.add(r);}}
            case "boundaries"->{var b=h.capabilities().boundary();boolean[] values={b.resourceMove(),b.crossDimensionTransfer(),b.escrowFreezesDecay(),b.remoteMachineRead(),b.remoteMachineOperate(),b.storeLivingEntities()};String[] names={"远程资源移动（预留）","跨维度转移","托管冻结衰变","远程机器读取","远程机器操作（不提供）","活体容器托管"};for(int i=0;i<values.length;i++)rows.add(row(AdminConfiguration.BOUNDARIES.get(i),names[i],values[i]));}
            case "deployments"->{for(Deployment d:h.deployments().deployments()){JsonObject r=row(d.appId(),d.appId()+" · 版本 "+h.version(d.packageDigest()),true);r.addProperty("digest",d.packageDigest());r.addProperty("everyone",AuthorityData.get(server).isEveryone(d.appId()));r.addProperty("playerCount",AuthorityData.get(server).playerCount(d.appId()));r.addProperty("version",Long.toString(h.version(d.packageDigest())));var policy=h.runtime().revocations().rule(d.appId());r.addProperty("minimum",Long.toString(policy==null?0:policy.minVersion()));r.addProperty("reason",policy==null?"":policy.reason());r.addProperty("followAuthor",h.runtime().followsAuthor(d.appId()));r.addProperty("frontendUpdate",h.runtime().frontendUpdate(d.appId()));r.addProperty("followUpdates",h.runtime().followsUpdates(d.appId()));rows.add(r);}}
            case "licenses"->{validApp(app);for(UUID uuid:AuthorityData.get(server).licensedPlayers(app)){JsonObject r=new JsonObject();r.addProperty("id",uuid.toString());r.addProperty("name",uuid.toString());r.addProperty("app",app);rows.add(r);}}
            case "authors"->{for(TrustStore.Author author:TrustStore.load(ServerPackageScanner.configPath(server)).authors()){JsonObject r=row(author.pubkeyBase64(),author.displayName(),!h.runtime().blockedAuthors().contains(author.pubkeyBase64()));r.addProperty("fingerprint",author.fingerprint());rows.add(r);}}
            case "economy"->{EconomyRuntime runtime=EconomyRuntime.current();if(runtime!=null&&runtime.registry()!=null)for(String id:runtime.registry().ids()){var provider=runtime.registry().get(id);JsonObject r=row(id,id,provider.isAvailable());r.addProperty("decimals",provider.currency().decimals());r.addProperty("audit",runtime.auditText(id));rows.add(r);}}
            case "pending"->{EconomyRuntime runtime=EconomyRuntime.current();Set<UUID> money=new HashSet<>();if(runtime!=null&&runtime.settlements()!=null)for(var e:runtime.settlements().entries())if(e.state()==SettlementJournal.State.UNKNOWN){rows.add(currency(e.id(),e.currency(),e.escrow()==null?null:e.escrow().owner(),e.escrow()==null?0:e.escrow().amount()));money.add(e.id());}for(var e:h.currencyEscrows().entries())if(e.state()==ScriptCurrencyEscrows.State.UNKNOWN&&money.add(e.id()))rows.add(currency(e.id(),e.currency(),e.scope().owner(),e.amount()));for(var e:h.escrow().entries())if(e.state()==ItemEscrowLedger.State.UNKNOWN_CAPTURE||e.state()==ItemEscrowLedger.State.UNKNOWN_DELIVERY){JsonObject r=row(e.id(),e.state()+" · "+e.owner(),false);r.addProperty("owner",e.owner().toString());r.addProperty("ledger","item");rows.add(r);}}
            default->throw new IllegalArgumentException("管理目录无效");
        }
        if(kind.equals("pending")){
            h.mailbox().snapshot().forEach((owner,entries)->{for(var entry:entries)if(entry.state()==MailboxLedger.State.UNKNOWN){JsonObject r=row(entry.id(),entry.incoming()?"收件箱搬入待核对":"收件箱领取待核对",false);r.addProperty("owner",owner.toString());r.addProperty("ledger","mailbox");rows.add(r);}});
            h.journal().forEach((owner,entries)->entries.forEach((id,entry)->{if(entry.state()==IdempotencyLedger.State.UNKNOWN){JsonObject r=row(id,"动作结果待核对 · "+owner,false);r.addProperty("owner",owner.toString());r.addProperty("ledger","guard");rows.add(r);}}));
        }return rows;
    }
    private static JsonObject row(String id,String name,boolean enabled){JsonObject r=new JsonObject();r.addProperty("id",id);r.addProperty("name",name);r.addProperty("enabled",enabled);return r;}
    private static JsonObject currency(UUID id,String currency,UUID owner,long amount){JsonObject r=row(id.toString(),currency+" · "+amount+" · "+(owner==null?"原主未知":owner),false);r.addProperty("owner",owner==null?"":owner.toString());r.addProperty("ledger","currency");r.addProperty("amount",Long.toString(amount));return r;}
    private JsonObject deployment(String app){validApp(app);Deployment d=ScriptHost.current().deployments().deployment(app);if(d==null)throw new IllegalArgumentException("部署不存在");JsonObject r=new Gson().toJsonTree(d).getAsJsonObject();r.addProperty("id",app);r.addProperty("everyone",AuthorityData.get(server).isEveryone(app));r.add("players",new Gson().toJsonTree(AuthorityData.get(server).licensedPlayers(app)));return r;}
    private JsonObject mutationState(JsonObject op){String kind=op.get("kind").getAsString();return switch(kind){
        case "license"->{AdminConfiguration.exact(op,"kind","app","mode","player");String mode=op.get("mode").getAsString();if(!Set.of("all","specific","revoke","unlicenseAll","clear").contains(mode))throw new IllegalArgumentException("许可操作无效");if(Set.of("specific","revoke").contains(mode))uuid(op.get("player").getAsString());if(mode.equals("revoke")&&AuthorityData.get(server).isEveryone(op.get("app").getAsString()))throw new IllegalArgumentException("请先取消所有人许可");yield deployment(op.get("app").getAsString());}
        case "remove"->{AdminConfiguration.exact(op,"kind","app");yield deployment(op.get("app").getAsString());}
        case "commandSwitch"->{AdminConfiguration.exact(op,"kind","enabled","others");for(String field:List.of("enabled","others"))if(!op.get(field).isJsonPrimitive()||!op.getAsJsonPrimitive(field).isBoolean())throw new IllegalArgumentException("命令开关须为布尔值");yield ScriptHost.current().commands().snapshot();}
        case "reload"->{AdminConfiguration.exact(op,"kind");JsonObject out=new JsonObject();out.add("当前生效",activeConfiguration());out.add("拟装载文件",new Gson().toJsonTree(readForReload()));yield out;}
        case "settlement"->{AdminConfiguration.exact(op,"kind","ledger","id","owner","occurred");if(!op.get("occurred").isJsonPrimitive()||!op.getAsJsonPrimitive("occurred").isBoolean())throw new IllegalArgumentException("核对结果必须是布尔值");yield settlement(op);}
        default->throw new IllegalArgumentException("写入类型无效");};}
    private JsonObject settlement(JsonObject op){String id=op.get("id").getAsString();ScriptHost h=ScriptHost.current();if(op.get("ledger").getAsString().equals("currency")){UUID uuid=uuid(id);JsonObject out=new JsonObject();EconomyRuntime runtime=EconomyRuntime.current();if(runtime!=null&&runtime.settlements()!=null)for(var e:runtime.settlements().entries())if(e.id().equals(uuid)&&e.state()==SettlementJournal.State.UNKNOWN)out.add("journal",new Gson().toJsonTree(e));for(var e:h.currencyEscrows().entries())if(e.id().equals(uuid)&&(e.state()==ScriptCurrencyEscrows.State.HELD||e.state()==ScriptCurrencyEscrows.State.UNKNOWN))out.add("scope",new Gson().toJsonTree(e));if(out.size()==0||!out.has("journal")&&out.getAsJsonObject("scope").get("state").getAsString().equals("HELD"))throw new IllegalArgumentException("待核对记录不存在");return out;}if(op.get("ledger").getAsString().equals("item"))for(var e:h.escrow().entries())if(e.id().equals(id)&&(e.state()==ItemEscrowLedger.State.UNKNOWN_CAPTURE||e.state()==ItemEscrowLedger.State.UNKNOWN_DELIVERY))return new Gson().toJsonTree(e).getAsJsonObject();if(op.get("ledger").getAsString().equals("mailbox")){UUID owner=uuid(op.get("owner").getAsString());for(var e:h.mailbox().snapshot().getOrDefault(owner,List.of()))if(e.id().equals(id)&&e.state()==MailboxLedger.State.UNKNOWN)return new Gson().toJsonTree(e).getAsJsonObject();}if(op.get("ledger").getAsString().equals("guard")){if(!id.matches("[0-9a-f]{64}"))throw new IllegalArgumentException("动作号无效");var e=h.journal().getOrDefault(uuid(op.get("owner").getAsString()),Map.of()).get(id);if(e!=null&&e.state()==IdempotencyLedger.State.UNKNOWN)return new Gson().toJsonTree(e).getAsJsonObject();}throw new IllegalArgumentException("待核对记录不存在");}
    private void mutate(UUID actor,JsonObject op)throws IOException {ScriptHost h=ScriptHost.current();switch(op.get("kind").getAsString()){
        case "commandSwitch"->{h.commands().switches(op.get("enabled").getAsBoolean(),op.get("others").getAsBoolean());h.broadcastHandshake();}
        case "reload"->{h.reloadRuntime();if(!ScriptHost.reloadCapabilities(server))throw new IllegalArgumentException("能力配置被拒绝");h.broadcastHandshake();}
        case "license"->{String app=op.get("app").getAsString();AuthorityData d=AuthorityData.get(server);switch(op.get("mode").getAsString()){case "all"->d.licenseAll(app);case "specific"->d.license(app,uuid(op.get("player").getAsString()));case "revoke"->d.revoke(app,uuid(op.get("player").getAsString()));case "unlicenseAll"->d.unlicenseAll(app);case "clear"->d.clearApp(app);}h.broadcastHandshake();}
        case "remove"->{String app=op.get("app").getAsString();h.deployments().remove(app);ScriptHost.reassemble(server,app);h.broadcastHandshake();}
        case "settlement"->{boolean occurred=op.get("occurred").getAsBoolean();String id=op.get("id").getAsString();if(op.get("ledger").getAsString().equals("item"))h.escrow().resolve(actor,id,occurred);else if(op.get("ledger").getAsString().equals("mailbox"))h.mailbox().resolve(actor,uuid(op.get("owner").getAsString()),id,occurred);else if(op.get("ledger").getAsString().equals("guard"))h.resolve(uuid(op.get("owner").getAsString()),id,occurred);else {UUID uuid=uuid(id);var r=EconomyRuntime.current();if(r!=null&&r.settlements()!=null&&r.settlements().entries().stream().anyMatch(e->e.id().equals(uuid)&&e.state()==SettlementJournal.State.UNKNOWN))r.settlements().resolve(uuid,occurred);h.currencyEscrows().settlementResolved(uuid,occurred);}}
    }}
    private JsonObject activeConfiguration(){ScriptHost h=ScriptHost.current();var out=new com.google.gson.JsonObject();out.addProperty("runtime",h.runtime().toString());var caps=new com.google.gson.JsonObject();caps.addProperty("preset",h.capabilities().preset().name());caps.add("disabled",new com.google.gson.Gson().toJsonTree(h.capabilities().disabled()));caps.add("boundary",new com.google.gson.Gson().toJsonTree(h.capabilities().boundary()));out.add("capabilities",caps);out.add("quotas",new com.google.gson.Gson().toJsonTree(h.quotas().current().values()));out.add("commands",h.commands().snapshot());out.add("resources",h.resourceConfiguration());return out;}
    private Map<String,JsonObject> readForReload(){try{Map<String,JsonObject> files=new LinkedHashMap<>(configs.read().files());java.nio.file.Path world=server.getWorldPath(LevelResource.ROOT);for(String name:List.of(CommandRunner.FILE,ResourceRegistry.FILE)){java.nio.file.Path file=world.resolve(name);if(java.nio.file.Files.isSymbolicLink(file)||java.nio.file.Files.size(file)>65536)throw new IOException("配置路径或长度无效");String raw=java.nio.file.Files.readString(file,StandardCharsets.UTF_8);if(com.november.mcphone.core.script.JsonScan.check(raw,8)!=null)throw new IOException("配置结构无效");JsonObject parsed=JsonParser.parseString(raw).getAsJsonObject();if(name.equals(CommandRunner.FILE))CommandRunner.validate(parsed);files.put(name,parsed);}ResourceRegistry.load(server);return files;}catch(IOException bad){throw new IllegalArgumentException("无法预览重载："+bad.getMessage(),bad);}}
    private void auditMutation(UUID actor,JsonObject before,JsonObject operation)throws IOException {
        ScriptHost h=ScriptHost.current();String app=subject(operation);long version=0;JsonObject after=operation.deepCopy();
        if(operation.has("app")){Deployment d=h.deployments().deployment(app);if(d!=null)version=h.version(d.packageDigest());}
        if(before.has("app")){app=before.get("app").getAsString();if(before.has("version"))version=before.get("version").getAsBigDecimal().longValueExact();}
        if(before.has("scope")){JsonObject scope=before.getAsJsonObject("scope").getAsJsonObject("scope");app=scope.get("app").getAsString();version=scope.get("version").getAsBigDecimal().longValueExact();}
        after.addProperty("version",Long.toString(version));h.quotas().audit().append(actor,"admin."+operation.get("kind").getAsString(),app,before,after);
    }
    private static void validApp(String app){if(app==null||app.length()>64||!app.matches("[a-z0-9_.-]+:[a-z0-9_./-]+"))throw new IllegalArgumentException("App ID 无效");}
    private static UUID uuid(String raw){UUID u=UUID.fromString(raw);if(!u.toString().equals(raw))throw new IllegalArgumentException("UUID 无效");return u;}
    private static String hash(JsonObject value){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(value.toString().getBytes(StandardCharsets.UTF_8)));}catch(Exception impossible){throw new AssertionError(impossible);}}
}
