package com.november.mcphone.core.script.server;

import com.google.gson.*;
import com.november.mcphone.MCphone;
import com.november.mcphone.core.script.net.*;
import com.november.mcphone.platform.StackCodecs;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.level.storage.LevelResource;
import net.minecraft.tags.TagKey;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceLocation;
import java.nio.charset.StandardCharsets;
import java.util.*;

/** 脚本只能提议，固定原生页面确认真实物品与固定收件人。所有物品 JSON 都来自服务端。 */
public final class ServerItemEscrow {
    private record Offer(String id,String app,String action,String revision,int slot,int count,UUID recipient,String snapshot,long expires,boolean destroy){}
    private static final TagKey<net.minecraft.world.item.Item> ALLOWED=TagKey.create(Registries.ITEM,ResourceLocation.fromNamespaceAndPath("mcphone","escrowable"));
    private static final TagKey<net.minecraft.world.item.Item> LIVING=TagKey.create(Registries.ITEM,ResourceLocation.fromNamespaceAndPath("mcphone","living_containers"));
    private final MinecraftServer server;private final ServerMailbox mailbox;private final ItemEscrowLedger ledger;private final Map<UUID,Offer> offers=new HashMap<>();
    public ServerItemEscrow(MinecraftServer server,ServerMailbox mailbox,java.util.function.Supplier<QuotaConfig> quotas){this.server=server;this.mailbox=mailbox;ledger=new ItemEscrowLedger(server.getWorldPath(LevelResource.ROOT).resolve("mcphone/item-escrow.json"),System::currentTimeMillis,quotas,mailbox::used);}
    public int used(UUID player){return ledger.used(player);}public int mailboxCount(UUID player){return ledger.mailboxCount(player);}
    private String encoded(ItemStack stack){return StackCodecs.encode(stack,server.registryAccess()).toString();}
    private void confirmation(ServerPlayer player,String app){ScriptHost host=ScriptHost.current();JsonObject data=new JsonObject();data.addProperty("app",app);data.addProperty("serverId",host.serverId().toString());data.addProperty("epoch",Long.toString(host.epoch(player.getUUID())));ScriptPushHandler.push(player,new ScriptPush(ScriptProtocol.HOST_APP_ID,"mcphone:escrow.proposal",data.toString().getBytes(StandardCharsets.UTF_8),Seq.next()));}
    private boolean allowed(ItemStack stack){ScriptHost host=ScriptHost.current();if((stack.getItem() instanceof net.minecraft.world.item.MobBucketItem||stack.is(LIVING))&&!host.capabilities().boundary().storeLivingEntities())return false;return stack.is(ALLOWED)&&!stack.isEmpty()&&(host.capabilities().boundary().escrowFreezesDecay()||StackCodecs.plain(stack));}
    private boolean capability(String app,boolean destroy){ScriptHost host=ScriptHost.current();Deployment d=host==null?null:host.deployments().deployment(app);return d!=null&&host.capabilityPolicy().check(destroy?"item.take.self":"trade.escrow",Set.copyOf(d.approvedCapabilities()))==CapabilityPolicy.Verdict.OK&&host.revocations(app).rejected(app,host.version(d.packageDigest()),d.packageDigest())==null;}
    public boolean propose(UUID owner,String app,String action,String revision,int slot,int count,UUID recipient,boolean destroy){offers.entrySet().removeIf(e->e.getValue().expires()<=System.currentTimeMillis());ServerPlayer player=server.getPlayerList().getPlayer(owner);if(player==null||!capability(app,destroy)||slot<0||slot>=36||count<1||count>64||offers.containsKey(owner)||offers.size()>=64||!destroy&&!ledger.canCapture(owner,app)||!destroy&&(owner.equals(recipient)||recipient==null||server.getPlayerList().getPlayer(recipient)==null))return false;ItemStack stack=player.getInventory().getItem(slot);if(stack.isEmpty()||stack.getCount()<count||!destroy&&!allowed(stack))return false;ItemStack copy=stack.copy();copy.setCount(count);String snapshot=encoded(copy);if(snapshot.length()>65536)return false;offers.put(owner,new Offer(UUID.randomUUID().toString().replace("-",""),app,action,revision,slot,count,recipient,snapshot,System.currentTimeMillis()+60000,destroy));confirmation(player,app);return true;}
    public ScriptRpcResult handle(ScriptRpc rpc,PlayerSnapshot player,JsonObject args){try{JsonObject result=new JsonObject();switch(rpc.actionId()){
        case "escrow.list"->{if(!args.keySet().equals(Set.of("offset")))throw new IllegalArgumentException();int offset=args.get("offset").getAsBigDecimal().intValueExact();if(offset<0||offset>4096)throw new IllegalArgumentException();JsonArray all=new JsonArray();Offer offer=offers.get(player.uuid());if(offer!=null&&offer.expires()>System.currentTimeMillis()){JsonObject row=preview(offer.id(),offer.app(),offer.snapshot());row.addProperty("proposal",true);row.addProperty("recipient",offer.destroy()?"销毁，不会发给任何人":offer.recipient().toString());row.addProperty("state","CONFIRM");all.add(row);}for(var e:ledger.entries())if(e.owner().equals(player.uuid())||e.recipient().equals(player.uuid())){JsonObject row=preview(e.id(),e.app(),e.stack());row.addProperty("proposal",false);row.addProperty("owner",e.owner().equals(player.uuid()));row.addProperty("recipient",e.recipient().toString());row.addProperty("state",e.state().name());all.add(row);}JsonArray rows=new JsonArray();for(int i=offset;i<Math.min(all.size(),offset+5);i++)rows.add(all.get(i));result.add("items",rows);result.addProperty("used",used(player.uuid()));result.addProperty("total",all.size());}
        case "escrow.confirm"->{if(args.size()!=1)throw new IllegalArgumentException();return ScriptRpcResult.fail(rpc.requestId(),confirm(player.uuid(),args.get("id").getAsString()));}
        case "escrow.accept","escrow.cancel"->{if(args.size()!=1)throw new IllegalArgumentException();var e=ledger.entry(args.get("id").getAsString());boolean cancel=rpc.actionId().equals("escrow.cancel");if(!(cancel?e.owner():e.recipient()).equals(player.uuid()))return ScriptRpcResult.fail(rpc.requestId(),ScriptErrorCode.NOT_AUTHORIZED);if(!cancel&&!capability(e.app(),false))return ScriptRpcResult.fail(rpc.requestId(),ScriptErrorCode.UNAVAILABLE);ServerPlayer live=server.getPlayerList().getPlayer(player.uuid());if(!cancel&&!ScriptHost.current().capabilities().boundary().crossDimensionTransfer()&&!live.level().dimension().location().toString().equals(e.dimension()))return ScriptRpcResult.fail(rpc.requestId(),ScriptErrorCode.NOT_AUTHORIZED);return ScriptRpcResult.fail(rpc.requestId(),deliver(e,cancel?e.owner():e.recipient()));}
        case "escrow.dismiss"->{if(args.size()!=0)throw new IllegalArgumentException();offers.remove(player.uuid());}
        default->throw new IllegalArgumentException();}return ScriptRpcResult.ok(rpc.requestId(),result.toString().getBytes(StandardCharsets.UTF_8),0);
    }catch(com.november.mcphone.core.script.server.store.StoreQuota.QuotaExceeded full){return ScriptRpcResult.fail(rpc.requestId(),ScriptErrorCode.QUOTA);}catch(IllegalArgumentException bad){return ScriptRpcResult.fail(rpc.requestId(),ScriptErrorCode.INVALID_ARGUMENT);}catch(RuntimeException bad){MCphone.LOGGER.error("[MCphone] 物品托管操作需检查",bad);return ScriptRpcResult.fail(rpc.requestId(),ScriptErrorCode.UNKNOWN);}}
    private JsonObject preview(String id,String app,String stack){ItemStack value=StackCodecs.decode(JsonParser.parseString(stack),server.registryAccess());JsonObject row=new JsonObject();row.addProperty("id",id);row.addProperty("app",app);row.addProperty("name",StoreRepository.clean(value.getHoverName().getString(),32));row.addProperty("count",value.getCount());return row;}
    private ScriptErrorCode confirm(UUID owner,String id){Offer offer=offers.get(owner);if(offer==null||!offer.id().equals(id)||offer.expires()<=System.currentTimeMillis())return ScriptErrorCode.INVALID_ARGUMENT;if(!capability(offer.app(),offer.destroy()))return ScriptErrorCode.UNAVAILABLE;ScriptHost host=ScriptHost.current();Deployment deployment=host.deployments().deployment(offer.app());if(!offer.revision().equals(deployment.revision())||!host.allows(owner,offer.app(),offer.action()))return ScriptErrorCode.NOT_AUTHORIZED;ServerPlayer player=server.getPlayerList().getPlayer(owner);if(player==null)return ScriptErrorCode.UNAVAILABLE;ItemStack stack=player.getInventory().getItem(offer.slot());if(stack.getCount()<offer.count())return ScriptErrorCode.INVALID_ARGUMENT;ItemStack copy=stack.copy();copy.setCount(offer.count());if(!encoded(copy).equals(offer.snapshot())||!offer.destroy()&&!allowed(copy))return ScriptErrorCode.INVALID_ARGUMENT;ItemEscrowLedger.Entry entry=ledger.capture(owner,offer.destroy()?owner:offer.recipient(),offer.app(),player.level().dimension().location().toString(),offer.snapshot(),offer.destroy(),offer.revision(),host.version(offer.revision()),Base64.getEncoder().encodeToString(host.author(offer.revision())));offers.remove(owner);
        try{audit(owner,"escrow.capture",entry);stack.shrink(offer.count());player.containerMenu.broadcastChanges();server.getPlayerList().saveAll();if(!com.november.mcphone.platform.PlayerSaves.inventoryConfirmed(player)){ledger.unknown(entry.id());return ScriptErrorCode.UNKNOWN;}ledger.held(entry.id());if(offer.destroy()){ledger.delivery(entry.id(),owner);audit(owner,"item.destroy",entry);ledger.complete(entry.id());}return ScriptErrorCode.OK;}catch(Exception bad){try{ledger.unknown(entry.id());}catch(RuntimeException ignored){}return ScriptErrorCode.UNKNOWN;}}
    private void audit(UUID actor,String action,ItemEscrowLedger.Entry e)throws java.io.IOException {ScriptHost.current().quotas().audit().append(actor,action,e.app(),null,new Gson().toJsonTree(e));}
    private ScriptErrorCode deliver(ItemEscrowLedger.Entry e,UUID target){if(e.state()!=ItemEscrowLedger.State.HELD)return ScriptErrorCode.UNKNOWN;try{audit(target,"escrow.delivery",e);ledger.delivery(e.id(),target);ItemStack stack=StackCodecs.decode(JsonParser.parseString(e.stack()),server.registryAccess());if(!mailbox.deposit(target,List.of(stack),"托管 "+e.app())){ledger.refused(e.id());return ScriptErrorCode.QUOTA;}ledger.complete(e.id());return ScriptErrorCode.OK;}catch(Exception bad){try{ledger.unknown(e.id());}catch(RuntimeException ignored){}return ScriptErrorCode.UNKNOWN;}}
    public void sweep(){long now=System.currentTimeMillis();offers.entrySet().removeIf(e->e.getValue().expires()<=now);for(var e:ledger.entries())if(e.state()==ItemEscrowLedger.State.HELD){if(e.expiresAt()<=now)deliver(e,e.owner());else if(e.expiresAt()-now<=3L*86400000&&server.getPlayerList().getPlayer(e.owner())!=null)ScriptHost.current().notifications().escrowWarning(e.owner(),e.id(),e.expiresAt()-now);}}
    public void forget(UUID player){offers.remove(player);}public List<ItemEscrowLedger.Entry> entries(){return ledger.entries();}
    public void resolve(UUID actor,String id,boolean occurred)throws java.io.IOException {audit(actor,occurred?"escrow.resolve.occurred":"escrow.resolve.retry",ledger.entry(id));ledger.resolve(id,occurred);}
}
